### ISSUE TITLE
KB instance not properly filtered when annotating

### ISSUE THREAD

**Issue by mromanello** [inception-project/inception#958]
**Describe the bug**

I have a KB connected to an annotation layer. For a given feature (`work_uri`) I specify its scope, in this case it can take as a value only instances of class `work`.
![image](https://user-images.githubusercontent.com/310693/52950555-ce81ff80-337f-11e9-83f9-1a5f909a9c8b.png)

Nevertheless, when annotating the dropdown menu for this feature is populated with strings attached to other instance types (e.g. `title`). 

**Expected behavior**

The dropdown for `work_uri` feature should contain only strings that in the KB are associated to instances of `work`.

**Please complete the following information:**
 - Version and build ID:0.7.2 (2019-01-30 17:46:49, build b490d4b8790c1c97df107762770f52dcd1b4fb8e)

----

- [x] Fix bug for the annotation page
- [x] Make sure the search field on the KB page also works well
- [x] Update documentation (developer and user documentation)

**Comment by reckart** [comment]
I'm afraid that filtering and full-text search are (currently) mutually exclusive. The filtering should work if you disable the full-text search capability in the KB settings. Thus, it should work ok for comparatively small KBs but won't work well for large KBs.

**Comment by mromanello** [comment]
Ok thanks. Actually, I could live with this behaviour ;-) the problem is that, if I disable the full-text search, it doesn't find any values at all. I wonder if it's normal? Or maybe I need to change some other settings?

![screen shot 2019-02-18 at 15 21 00](https://user-images.githubusercontent.com/310693/52956993-f332a300-3390-11e9-884e-873d439b44be.png)

**Comment by reckart** [comment]
https://github.com/inception-project/inception/pull/912 might fix that problem.

**Comment by reckart** [comment]
@mromanello could you test with the changes from #912 or tell me how to configure the KB so I can test with your settings?

**Comment by mromanello** [comment]
> @mromanello could you test with the changes from #912 or tell me how to configure the KB so I can test with your settings?

hi @reckart sorry, I won't be able to test this soon-ish, but here are my KB settings:

![image](https://user-images.githubusercontent.com/310693/53181998-e7491a00-35f8-11e9-8077-6648e6ef846a.png)
![image](https://user-images.githubusercontent.com/310693/53182006-ec0dce00-35f8-11e9-8032-b783ff349699.png)

just ping me if you need more info.

**Comment by reckart** [comment]
The bug is fixed now. I'm leaving the issue open because there was quite a bit of refactoring and the documentation still needs to be updated.

**Comment by reckart** [comment]
Auto-complete on the annotation page looks good.

Auto-complete on the KB page doesn't look good atm.

**Comment by reckart** [comment]
https://github.com/inception-project/inception/pull/978 resolves the other two todos in the initial description: 

* Make sure the search field on the KB page also works well
* Update documentation (developer and user documentation)

Once this is merged, this issue can be closed. 

For additional improvements/refactorings new issues will be opened.

**Comment by mromanello** [comment]
Hi Guys,

I've finally managed to test this also with 0.8.1 but I'm still having the same issue (see screenshots below). I turned off the fuzzy matching (Virtuoso triple store) but the autocomplete still displays a bunch of false positives (labels coming from instances of other classes). 

But maybe I'm doing something wrong ?

![image](https://user-images.githubusercontent.com/310693/54427345-8bb30d80-471a-11e9-818f-37c92e25079f.png)

![image](https://user-images.githubusercontent.com/310693/54427402-b2714400-471a-11e9-9698-bc84522ee673.png)

![image](https://user-images.githubusercontent.com/310693/54427434-c61caa80-471a-11e9-8bf7-c47d5554e2e3.png)

**Comment by reckart** [comment]
No, you're doing everything right. I have obviously not properly completed the implementation. While I did implement the *ability* to limit to a scope and even added tests, I forgot to actually pass on the configured scope to the query code... *sigh*.

Anyway - it was a quick fix now and will be in 0.8.2.

**Comment by mromanello** [comment]
just to confirm that it works like a charm now! thanks :100:
